# tasks file for php5
- hosts: web
  become_user: root
  tasks:
  
  - name: Install php
    apt: name= {{ item }} state=present update_cache=true
    with_items:
       - php5*
       - php5-curl*
       - php5-intl*
       - php5-mcrypt*
       - php5-memcache*
       - php5-memcached*
       - php5-devel*
       - php5-mysql*
       - php5-gd*
       - php5-xdebug*
       - phpmyadmin   

