---
# tasks file for mysql
- hosts: web
  become_user: root
 
  tasks:
  - name: Installing
    apt: pkg=mysql-server* state=present update_cache=yes
  - name: Execute  
    shell: name= {{ item }}
    with_items:
      - echo mysql-server-5.1 mysql-server/root_password password root| debconf-set-selections
      - echo mysql-server-5.1 mysql-server/root_password_again password root| debconf-set-selections
   
  - ufw: state=disabled
