---
- name: Install list of packages for Team viewer
  hosts: webabhi
  become_user: root
  tasks:
  - name: Execute
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - libxtst6:i386
      - gcc-4.8-base:i386
      - libc6:i386
      - libgcc1:i386
      - libx11-6:i386
      - libxau6:i386
      - libxcb1:i386
      - libxdmcp6:i386
      - libxext6:i386
      - libjpeg62:i386
      - libxinerama1:i386
  
  - name: Installing now
    get_url:
     url: http://download.teamviewer.com/download/teamviewer_amd64.deb
     dest: /tmp

  



